# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'PromiseKit', '~> 6.8'
end
